# Generated by Django 5.2.6 on 2025-09-08 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='Имя тега')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ')),
                ('status', models.CharField(choices=[('New', 'New'), ('In_progress', 'In_progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='New', max_length=15, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium'), ('Very High', 'Very High')], max_length=15, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('due_date', models.DateTimeField(verbose_name='срок выполнения')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project', verbose_name='Проект')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='project.tag', verbose_name='Теги')),
            ],
        ),
    ]
