# Generated by Django 5.2.6 on 2025-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='projects/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания файла')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-title'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', '-priority'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'project')},
        ),
    ]
