# Generated by Django 5.2.6 on 2025-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Файл проекта', 'verbose_name_plural': 'Файлы проекта'},
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(related_name='projects', to='project.projectfile', verbose_name='Файлы проекта'),
        ),
    ]
