# Generated by Django 5.2.6 on 2025-09-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectfile_options_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High'), ('Extra', 'Extra'), ('A', 'A'), ('Urgent', 'Urgent')], max_length=15, verbose_name='Приоритет'),
        ),
    ]
